global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'opa-spring-boot'
    static_configs:
      - targets: ['app:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'opa-server'
    static_configs:
      - targets: ['opa:8181']
    metrics_path: '/metrics'
    scrape_interval: 10s
